'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class XMLImportExport

  '''<summary>
  '''lnkXml control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkXml As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''uploadXml control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents uploadXml As Global.System.Web.UI.WebControls.FileUpload

  '''<summary>
  '''vldUploadXml control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldUploadXml As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnUpload control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''GridViewDataSetExisting control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewDataSetExisting As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''GridViewDataSetNew control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewDataSetNew As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''btnImport control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button
End Class
