'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class AddBooks

  '''<summary>
  '''pnlByHand control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlByHand As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtIsbn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtIsbn As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSummary control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSummary As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtNotes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtPageCount control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPageCount As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldPageCount control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldPageCount As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtPrice control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldPageCp control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldPageCp As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''PubDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PubDate As Global.System.Web.UI.WebControls.Calendar

  '''<summary>
  '''ddlPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlPublisher As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''vldPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldPublisher As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ddlSubjectByHand control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlSubjectByHand As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''vldSubjectByHand control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldSubjectByHand As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnAddByHand control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddByHand As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''pnlSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtSearchKeywords control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSearchKeywords As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldSearchKeywords control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldSearchKeywords As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtSearchPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSearchPublisher As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''updAmazonBooks control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAmazonBooks As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewAmazonBooks control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewAmazonBooks As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''divImport control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divImport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ddlSubjectFromAmazon control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlSubjectFromAmazon As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''vldSubjectFromAmazon control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldSubjectFromAmazon As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnImport control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button
End Class
