'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Authors

  '''<summary>
  '''updAuthors control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAuthors As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewAuthors control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewAuthors As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''UpdateProgressAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressAddAuthor As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAddAuthor As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''btnShowAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnShowAddAuthor As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divAddAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''txtFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddAuthor As Global.System.Web.UI.WebControls.Button
End Class
