'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Books

  '''<summary>
  '''lnkAddBooks control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkAddBooks As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''LinqDataSource1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LinqDataSource1 As Global.System.Web.UI.WebControls.LinqDataSource

  '''<summary>
  '''updBooks control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updBooks As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewBooks control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewBooks As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''lblTotalPrice control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTotalPrice As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lnkBiggestBook control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkBiggestBook As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''lblPageCount control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPageCount As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lnkBestBook control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkBestBook As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''lblRating control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRating As Global.System.Web.UI.WebControls.Label
End Class
