'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class BookPage

  '''<summary>
  '''updBookDetails control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updBookDetails As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''DetailsView1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DetailsView1 As Global.System.Web.UI.WebControls.DetailsView

  '''<summary>
  '''btnDelete control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''UpdateProgressAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressAddAuthor As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAddAuthor As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''btnShowAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnShowAddAuthor As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divAddAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ddlAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlAuthor As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''vldAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldAuthor As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnAddAuthor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddAuthor As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''UpdateProgressAddReview control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressAddReview As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updReviews control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updReviews As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewReviews control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewReviews As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''btnShowAddReview control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnShowAddReview As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divAddReview control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divAddReview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ReviewRating control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReviewRating As Global.AjaxControlToolkit.Rating

  '''<summary>
  '''txtReviewComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtReviewComments As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnAddReview control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddReview As Global.System.Web.UI.WebControls.Button
End Class
