'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Publishers

  '''<summary>
  '''updPublishers control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updPublishers As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewPublishers control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewPublishers As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''UpdateProgressAddPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressAddPublisher As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updAddPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAddPublisher As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''btnShowAddPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnShowAddPublisher As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divAddPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divAddPublisher As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''txtName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnAddPublisher control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddPublisher As Global.System.Web.UI.WebControls.Button
End Class
