'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1426
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Subjects

  '''<summary>
  '''updSubjects control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updSubjects As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''GridViewSubjects control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GridViewSubjects As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''UpdateProgressAddSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressAddSubject As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updAddSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updAddSubject As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''btnShowAddSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnShowAddSubject As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''divAddSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divAddSubject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''txtName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''vldName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents vldName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''btnAddSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddSubject As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''UpdateProgressDalSample control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdateProgressDalSample As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''updDalSample control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents updDalSample As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''ddlSubject control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlSubject As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''BookListDalSample control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookListDalSample As Global.LinqBooks.Web.BookList
End Class
